src/gz all http://lcpd.itg.ti.com/builds/arago-master/rt/am62xx-evm/latest/packages/all
src/gz any http://lcpd.itg.ti.com/builds/arago-master/rt/am62xx-evm/latest/packages/any
src/gz noarch http://lcpd.itg.ti.com/builds/arago-master/rt/am62xx-evm/latest/packages/noarch
src/gz aarch64 http://lcpd.itg.ti.com/builds/arago-master/rt/am62xx-evm/latest/packages/aarch64
src/gz am62xx_evm http://lcpd.itg.ti.com/builds/arago-master/rt/am62xx-evm/latest/packages/am62xx_evm
