set -e
set +e
if [ -n "$D" ]; then
    ln -sf fitImage-6.6.32-rt32-ti-rt-g04a9ad081f0f-dirty $D/boot/fitImage > /dev/null 2>&1
else
    ln -sf fitImage-6.6.32-rt32-ti-rt-g04a9ad081f0f-dirty boot/fitImage > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "Filesystem on boot/ doesn't support symlinks, falling back to copied image (fitImage)."
        install -m 0644 boot/fitImage-6.6.32-rt32-ti-rt-g04a9ad081f0f-dirty boot/fitImage
    fi
fi
set -e
